<a href="https://colab.research.google.com/github/hoin1357/BigDataPrograming_task/blob/main/6w_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [111]:
import pandas as pd
df = pd.DataFrame([{'국어': 70, '수학': 89, '영어': 90},
                   {'국어': 80, '영어': 99},
                   {'수학': 66, '영어': 78}])
df

     국어    수학  영어
0  70.0  89.0  90
1  80.0   NaN  99
2   NaN  66.0  78

In [112]:
s1 = pd.Series([90, 80, 60, 66])
s2 = pd.Series([45, 73, 83, 99])
s3 = pd.Series([92, 75, 82, 75])
s1

0    90
1    80
2    60
3    66
dtype: int64

In [113]:
df = pd.DataFrame({'국어': s1, '수학': s2, '영어': s3})
df

   국어  수학  영어
0  90  45  92
1  80  73  75
2  60  83  82
3  66  99  75

In [114]:
df.index = ['노', '장', '박', '강']
df

   국어  수학  영어
노  90  45  92
장  80  73  75
박  60  83  82
강  66  99  75

In [115]:
df = pd.DataFrame({'A': pd.Series([10, 20, 30], index=[0, 1, 2]),
                   'B': pd.Series([3, 2, 1], index=[1, 2, 3])})
df

      A    B
0  10.0  NaN
1  20.0  3.0
2  30.0  2.0
3   NaN  1.0

In [116]:
s1 = pd.Series([90, 80, 60], index=['노', '장', '박'])
s2 = pd.Series([45, 73, 99], index=['장', '박', '강'])
s3 = pd.Series([92, 75, 82, 75])

df = pd.DataFrame({'국어': s1, '영어': s2, '수학': s3},
                  index=['노', '장', '박', '강'])
df

     국어    영어  수학
노  90.0   NaN NaN
장  80.0  45.0 NaN
박  60.0  73.0 NaN
강   NaN  99.0 NaN

In [117]:
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
df

   col1  col2
0     1     3
1     2     4

In [118]:
df.dtypes

col1    int64
col2    int64
dtype: object

In [119]:
df = pd.DataFrame(data=d, dtype=np.int8)
df.dtypes

col1    int8
col2    int8
dtype: object

In [120]:
dates = pd.date_range("20250101", periods=6)
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06'],
              dtype='datetime64[ns]', freq='D')

In [121]:
dates[0]

Timestamp('2025-01-01 00:00:00')

In [122]:
dates = pd.date_range("20250101", end='20250110')
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', freq='D')

In [123]:
dates = pd.date_range("20250101", periods=6, freq='3D')
dates

DatetimeIndex(['2025-01-01', '2025-01-04', '2025-01-07', '2025-01-10',
               '2025-01-13', '2025-01-16'],
              dtype='datetime64[ns]', freq='3D')

In [124]:
dates = pd.date_range("20250101", periods=6, freq='3H')
dates

/tmp/ipykernel_679/3819429892.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range("20250101", periods=6, freq='3H')

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 03:00:00',
               '2025-01-01 06:00:00', '2025-01-01 09:00:00',
               '2025-01-01 12:00:00', '2025-01-01 15:00:00'],
              dtype='datetime64[ns]', freq='3h')

In [125]:
dates = pd.date_range("20250101", periods=6, freq='W')
dates

DatetimeIndex(['2025-01-05', '2025-01-12', '2025-01-19', '2025-01-26',
               '2025-02-02', '2025-02-09'],
              dtype='datetime64[ns]', freq='W-SUN')

In [126]:
dates = pd.date_range("20260101", periods=6, freq='W-SUN')
dates

DatetimeIndex(['2026-01-04', '2026-01-11', '2026-01-18', '2026-01-25',
               '2026-02-01', '2026-02-08'],
              dtype='datetime64[ns]', freq='W-SUN')

In [127]:
dates = pd.date_range("20260101", periods=6, freq='W-TUE')
dates

DatetimeIndex(['2026-01-06', '2026-01-13', '2026-01-20', '2026-01-27',
               '2026-02-03', '2026-02-10'],
              dtype='datetime64[ns]', freq='W-TUE')

In [128]:
dates = pd.date_range("20260101", periods=6, freq='W-FRI')
dates

DatetimeIndex(['2026-01-02', '2026-01-09', '2026-01-16', '2026-01-23',
               '2026-01-30', '2026-02-06'],
              dtype='datetime64[ns]', freq='W-FRI')

In [129]:
dates = pd.date_range("20250101", periods=6, freq='M')
dates

/tmp/ipykernel_679/746379463.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range("20250101", periods=6, freq='M')

DatetimeIndex(['2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30'],
              dtype='datetime64[ns]', freq='ME')

In [130]:
dates = pd.date_range("20250101", periods=6, freq='MS')
dates

DatetimeIndex(['2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01',
               '2025-05-01', '2025-06-01'],
              dtype='datetime64[ns]', freq='MS')

In [131]:
import pandas as pd
import numpy as np

dates=pd.date_range("20260408",periods=6)
dates

DatetimeIndex(['2026-04-08', '2026-04-09', '2026-04-10', '2026-04-11',
               '2026-04-12', '2026-04-13'],
              dtype='datetime64[ns]', freq='D')

In [132]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2026-04-08  0.298954  1.647168  0.801066 -0.606500
2026-04-09  0.903721 -0.610959 -0.737427  1.241984
2026-04-10 -0.692144 -1.941376  0.295381 -1.342808
2026-04-11 -0.453252  0.376558  1.351884 -0.468927
2026-04-12  0.410103  1.051098  1.197062  0.634981
2026-04-13 -1.033874 -0.072990 -1.681517 -1.682268

In [133]:
df2 = pd.DataFrame({
    "A": 1.0,
    "B": pd.Timestamp("20260302"),
    "C": pd.Series(np.arange(1, 3, .5)),
    "D": np.array([3] * 4, dtype="int32"),
    "E": pd.Categorical(["test", "train", "test", "train"]),
    "F": "foo"
})
df2

     A          B    C  D      E    F
0  1.0 2026-03-02  1.0  3   test  foo
1  1.0 2026-03-02  1.5  3  train  foo
2  1.0 2026-03-02  2.0  3   test  foo
3  1.0 2026-03-02  2.5  3  train  foo

In [134]:
dates=pd.date_range("20260408",end="20260420")
dates

DatetimeIndex(['2026-04-08', '2026-04-09', '2026-04-10', '2026-04-11',
               '2026-04-12', '2026-04-13', '2026-04-14', '2026-04-15',
               '2026-04-16', '2026-04-17', '2026-04-18', '2026-04-19',
               '2026-04-20'],
              dtype='datetime64[ns]', freq='D')

In [135]:
df2.dtypes

A          float64
B    datetime64[s]
C          float64
D            int32
E         category
F           object
dtype: object

#데이터 프레임 참조

In [136]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
                  columns=['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [137]:
pf['중간']
# 또는 pf.중간

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [138]:
pf['출석']

윤일형    18
강수희    20
홍소희    19
유한빈    20
신수빈    16
Name: 출석, dtype: int64

In [139]:
pf[['출석']]

     출석
윤일형  18
강수희  20
홍소희  19
유한빈  20
신수빈  16

In [140]:
pf[['기말', '출석', '중간']]

     기말  출석  중간
윤일형  35  18  25
강수희  27  20  18
홍소희  17  19  17
유한빈  22  20  12
신수빈  34  16  22

In [141]:
pf[['기말']]

     기말
윤일형  35
강수희  27
홍소희  17
유한빈  22
신수빈  34

In [142]:
pf[pf['중간'] > 20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [143]:
pf[pf['중간'] > 20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [144]:
pf[(pf['출석'] >= 19) & (pf['기말'] >= 20)]

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

In [145]:
pf.loc['윤일형']

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [146]:
pf.loc[['윤일형']]

     중간  기말  과제  출석
윤일형  25  35   8  18

In [147]:
pf.loc[['홍소희', '윤일형']]

     중간  기말  과제  출석
홍소희  17  17  10  19
윤일형  25  35   8  18

In [148]:
pf.loc['윤일형':'유한빈']

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [149]:
pf.loc[pf.중간 > 20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [150]:
pf.loc[(pf.중간 > 10) & (pf.과제 == 10)]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19

In [151]:
pf.loc[pf.index[0]] # 첫 번째 행 검색

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [152]:
pf.loc[[pf.index[0]]] # 첫 번째 행 검색

     중간  기말  과제  출석
윤일형  25  35   8  18

In [153]:
pf.loc[pf.index[1:4]] # 슬라이싱 행 검색

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [154]:
pf.loc[pf.index[1:4]][['기말', '과제']]

     기말  과제
강수희  27  10
홍소희  17  10
유한빈  22   9

In [155]:
pf.loc[:, '과제']

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [156]:
pf.loc[:, '중간':'과제']

     중간  기말  과제
윤일형  25  35   8
강수희  18  27  10
홍소희  17  17  10
유한빈  12  22   9
신수빈  22  34   8

In [157]:
pf.loc[:, ['기말', '출석']]

     기말  출석
윤일형  35  18
강수희  27  20
홍소희  17  19
유한빈  22  20
신수빈  34  16

#데이터프레임 정보와 조건 검색

In [158]:
import pandas as pd
df = pd.read_csv('2016년졸음운전.csv',
                 encoding='euc-kr', index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 2016년1월 to 2016년12월
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사고(건)   12 non-null     int64
 1   사망(명)   12 non-null     int64
 2   부상(명)   12 non-null     int64
dtypes: int64(3)
memory usage: 384.0+ bytes

In [160]:
df.describe()

            사고(건)      사망(명)       부상(명)
count   12.000000  12.000000   12.000000
mean   202.750000   8.166667  408.250000
std     23.014324   3.186144   60.051682
min    168.000000   4.000000  328.000000
25%    186.000000   5.750000  363.500000
50%    200.000000   7.000000  402.500000
75%    219.500000  10.500000  441.250000
max    239.000000  13.000000  522.000000

In [161]:
df.T

연월,2016년1월,2016년2월,2016년3월,2016년4월,2016년5월,2016년6월,2016년7월,2016년8월,2016년9월,2016년10월,2016년11월,2016년12월
사고(건),192,174,217,216,239,200,227,230,187,183,200,168
사망(명),5,6,7,7,13,12,9,7,13,10,5,4
부상(명),387,328,435,419,522,362,460,490,347,367,418,364

In [162]:
df.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [163]:
df.sum(axis=0)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [164]:
df.sum(axis=1)

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64

In [165]:
df.cumsum()

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [166]:
df.cumsum(axis=0)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [167]:
df.cumsum(axis=1)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

In [168]:
from IPython.display import display_html
def display_side_by_side(*args):
    """여러 데이터프레임 비교가 쉽게 옆쪽으로 표시한다"""
    html_str=''
    for df in args:
        html_str += df.to_html() + '&nbsp;'*4
    display_html(html_str.replace('table','table style="display:inline"'), raw=True)

In [169]:
display_side_by_side(df,df.cumsum(axis=1))

,사고(건),사망(명),부상(명)
연월,,,
2016년1월,192,5,387
2016년2월,174,6,328
2016년3월,217,7,435
2016년4월,216,7,419
2016년5월,239,13,522
2016년6월,200,12,362
2016년7월,227,9,460
2016년8월,230,7,490
2016년9월,187,13,347
2016년10월,183,10,367
2016년11월,200,5,418
2016년12월,168,4,364
,사고(건),사망(명),부상(명)
연월,,,
2016년1월,192,197,584
2016년2월,174,180,508
2016년3월,217,224,659
2016년4월,216,223,642
2016년5월,239,252,774
2016년6월,200,212,574
2016년7월,227,236,696
2016년8월,230,237,727
2016년9월,187,200,547
2016년10월,183,193,560
2016년11월,200,205,623
2016년12월,168,172,536

In [170]:
df.mean()

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [171]:
df.mean(axis=0)

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [172]:
df.mean(axis=1)

연월
2016년1월     194.666667
2016년2월     169.333333
2016년3월     219.666667
2016년4월     214.000000
2016년5월     258.000000
2016년6월     191.333333
2016년7월     232.000000
2016년8월     242.333333
2016년9월     182.333333
2016년10월    186.666667
2016년11월    207.666667
2016년12월    178.666667
dtype: float64

In [173]:
df.mean(axis=None)

np.float64(206.38888888888889)

In [174]:
df.max()

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [175]:
df.max(axis=0)

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [176]:
df.max(axis=1)

연월
2016년1월     387
2016년2월     328
2016년3월     435
2016년4월     419
2016년5월     522
2016년6월     362
2016년7월     460
2016년8월     490
2016년9월     347
2016년10월    367
2016년11월    418
2016년12월    364
dtype: int64

In [177]:
df.max(axis=None)

522

In [178]:
df.min()

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [179]:
df.min(axis=0)

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [180]:
df.min(axis=1)

연월
2016년1월      5
2016년2월      6
2016년3월      7
2016년4월      7
2016년5월     13
2016년6월     12
2016년7월      9
2016년8월      7
2016년9월     13
2016년10월    10
2016년11월     5
2016년12월     4
dtype: int64

In [181]:
df.min(axis=None)

4

In [182]:
df2 = df.copy()
df2['재해지수'] = df[['사망(명)', '부상(명)']].sum(axis=1)
df2

          사고(건)  사망(명)  부상(명)  재해지수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [183]:
df2.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
재해지수     4997
dtype: int64

In [184]:
df2.loc['총계'] = df2.sum(axis=0)
df2

          사고(건)  사망(명)  부상(명)  재해지수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368
총계         2433     98   4899  4997

In [185]:
df2 > 10

          사고(건)  사망(명)  부상(명)  재해지수
연월
2016년1월    True  False   True  True
2016년2월    True  False   True  True
2016년3월    True  False   True  True
2016년4월    True  False   True  True
2016년5월    True   True   True  True
2016년6월    True   True   True  True
2016년7월    True  False   True  True
2016년8월    True  False   True  True
2016년9월    True   True   True  True
2016년10월   True  False   True  True
2016년11월   True  False   True  True
2016년12월   True  False   True  True
총계         True   True   True  True

In [186]:
df2[df2 > 10]

          사고(건)  사망(명)  부상(명)  재해지수
연월
2016년1월     192    NaN    387   392
2016년2월     174    NaN    328   334
2016년3월     217    NaN    435   442
2016년4월     216    NaN    419   426
2016년5월     239   13.0    522   535
2016년6월     200   12.0    362   374
2016년7월     227    NaN    460   469
2016년8월     230    NaN    490   497
2016년9월     187   13.0    347   360
2016년10월    183    NaN    367   377
2016년11월    200    NaN    418   423
2016년12월    168    NaN    364   368
총계         2433   98.0   4899  4997

In [187]:
df2[ [True]*6 + [False]*7 ]

         사고(건)  사망(명)  부상(명)  재해지수
연월
2016년1월    192      5    387   392
2016년2월    174      6    328   334
2016년3월    217      7    435   442
2016년4월    216      7    419   426
2016년5월    239     13    522   535
2016년6월    200     12    362   374

In [188]:
df2

          사고(건)  사망(명)  부상(명)  재해지수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368
총계         2433     98   4899  4997

In [189]:
df2['재해지수'] > 400

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월      True
2016년6월     False
2016년7월      True
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월     True
2016년12월    False
총계           True
Name: 재해지수, dtype: bool

In [190]:
df2[df2['재해지수'] > 400]

          사고(건)  사망(명)  부상(명)  재해지수
연월
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년11월    200      5    418   423
총계         2433     98   4899  4997

In [191]:
df['사망(명)'] == 7

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [192]:
df['사망(명)'].isin([7])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [193]:
df['사망(명)'].isin([7, 10])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월     True
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [194]:
df[ (df['사망(명)'].isin([7, 10])) | (df['부상(명)'] > 350) ]

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [195]:
df[ df.index.str.contains('3')]

         사고(건)  사망(명)  부상(명)
연월
2016년3월    217      7    435

In [196]:
df3 = df.copy()
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [197]:
df3[df3 > 10] = -df3
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월    -192      5   -387
2016년2월    -174      6   -328
2016년3월    -217      7   -435
2016년4월    -216      7   -419
2016년5월    -239    -13   -522
2016년6월    -200    -12   -362
2016년7월    -227      9   -460
2016년8월    -230      7   -490
2016년9월    -187    -13   -347
2016년10월   -183     10   -367
2016년11월   -200      5   -418
2016년12월   -168      4   -364

In [198]:
df = pd.DataFrame({'A': range(1, 6),
                   'B': range(6, -3, -2),
                   'C': range(10, 5, -1),
                   'D clmns': range(3, -2, -1),
                   'E': ['python', 'java', 'python', 'go', 'python']})
df

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [199]:
df.query('A > B')

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [200]:
df[df.A > df.B]

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [201]:
df.query('C == 10')

   A  B   C  D clmns       E
0  1  6  10        3  python

In [202]:
df.query('A > 0')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [203]:
df.query('E == "python"')

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [204]:
df.query("E != 'python'")

   A  B  C  D clmns     E
1  2  4  9        2  java
3  4  0  7        0    go

In [205]:
df.query('A==`D clmns`')

   A  B  C  D clmns     E
1  2  4  9        2  java

In [206]:
df.query('A=="D clmns"')

Empty DataFrame
Columns: [A, B, C, D clmns, E]
Index: []

In [207]:
df[df.A==df["D clmns"]]

   A  B  C  D clmns     E
1  2  4  9        2  java

In [208]:
df.query('A>3|B>8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [209]:
df.query('A>2&C<8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [210]:
df.query("E in ['python','go']")

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [211]:
num=3
df.query('B>@num')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [212]:
num=3
df.query(f'B>{num}')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [213]:
s="E.str.contains('py')"
df.query(s)

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [214]:
s='E.str.startswith("g")'
df.query(s)

   A  B  C  D clmns   E
3  4  0  7        0  go

In [215]:
s="E.str.endswith('on')"
df.query(s)

## 17p까지 완료

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [216]:
df.head()

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [217]:
df.head(7)

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [218]:
df.tail()

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [219]:
df.tail(6)

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [220]:
df.sort_index()

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [221]:
df.sort_index(axis=0)

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [222]:
df.sort_index(ascending=False)

   A  B   C  D clmns       E
4  5 -2   6       -1  python
3  4  0   7        0      go
2  3  2   8        1  python
1  2  4   9        2    java
0  1  6  10        3  python

In [225]:
import pandas as pd
df = pd.read_csv('2016년졸음운전.csv',
                 encoding='euc-kr', index_col=0)

In [226]:
df.sort_values(by='사망(명)')

          사고(건)  사망(명)  부상(명)
연월
2016년12월    168      4    364
2016년1월     192      5    387
2016년11월    200      5    418
2016년2월     174      6    328
2016년8월     230      7    490
2016년4월     216      7    419
2016년3월     217      7    435
2016년7월     227      9    460
2016년10월    183     10    367
2016년6월     200     12    362
2016년5월     239     13    522
2016년9월     187     13    347

In [227]:
df.sort_values(by=['사망(명)', '부상(명)'])

          사고(건)  사망(명)  부상(명)
연월
2016년12월    168      4    364
2016년1월     192      5    387
2016년11월    200      5    418
2016년2월     174      6    328
2016년4월     216      7    419
2016년3월     217      7    435
2016년8월     230      7    490
2016년7월     227      9    460
2016년10월    183     10    367
2016년6월     200     12    362
2016년9월     187     13    347
2016년5월     239     13    522

In [228]:
df.sort_values(by='2016년12월', axis=1)

          사망(명)  사고(건)  부상(명)
연월
2016년1월       5    192    387
2016년2월       6    174    328
2016년3월       7    217    435
2016년4월       7    216    419
2016년5월      13    239    522
2016년6월      12    200    362
2016년7월       9    227    460
2016년8월       7    230    490
2016년9월      13    187    347
2016년10월     10    183    367
2016년11월      5    200    418
2016년12월      4    168    364

In [229]:
df.sort_values(by='2016년12월', axis=1, ascending=False)

          부상(명)  사고(건)  사망(명)
연월
2016년1월     387    192      5
2016년2월     328    174      6
2016년3월     435    217      7
2016년4월     419    216      7
2016년5월     522    239     13
2016년6월     362    200     12
2016년7월     460    227      9
2016년8월     490    230      7
2016년9월     347    187     13
2016년10월    367    183     10
2016년11월    418    200      5
2016년12월    364    168      4

In [230]:
dates = pd.date_range('20240102', periods=6)
df_new = pd.DataFrame(np.arange(24).reshape(6, 4), index=dates)

df_new

             0   1   2   3
2024-01-02   0   1   2   3
2024-01-03   4   5   6   7
2024-01-04   8   9  10  11
2024-01-05  12  13  14  15
2024-01-06  16  17  18  19
2024-01-07  20  21  22  23

In [231]:
df_new.columns = list('ABCD')
df_new

             A   B   C   D
2024-01-02   0   1   2   3
2024-01-03   4   5   6   7
2024-01-04   8   9  10  11
2024-01-05  12  13  14  15
2024-01-06  16  17  18  19
2024-01-07  20  21  22  23

In [232]:
s1 = pd.Series([1, 2, 3, 4, 5], index=pd.date_range('20240102', periods=5))
s1

2024-01-02    1
2024-01-03    2
2024-01-04    3
2024-01-05    4
2024-01-06    5
Freq: D, dtype: int64

In [233]:
df_new['E'] = s1
df_new

             A   B   C   D    E
2024-01-02   0   1   2   3  1.0
2024-01-03   4   5   6   7  2.0
2024-01-04   8   9  10  11  3.0
2024-01-05  12  13  14  15  4.0
2024-01-06  16  17  18  19  5.0
2024-01-07  20  21  22  23  NaN

In [234]:
df.loc['2024-01-02', 'A'] = 10
df

            사고(건)  사망(명)  부상(명)     A
연월
2016년1월     192.0    5.0  387.0   NaN
2016년2월     174.0    6.0  328.0   NaN
2016년3월     217.0    7.0  435.0   NaN
2016년4월     216.0    7.0  419.0   NaN
2016년5월     239.0   13.0  522.0   NaN
2016년6월     200.0   12.0  362.0   NaN
2016년7월     227.0    9.0  460.0   NaN
2016년8월     230.0    7.0  490.0   NaN
2016년9월     187.0   13.0  347.0   NaN
2016년10월    183.0   10.0  367.0   NaN
2016년11월    200.0    5.0  418.0   NaN
2016년12월    168.0    4.0  364.0   NaN
2024-01-02    NaN    NaN    NaN  10.0

In [235]:
df.loc[dates[1], 'B'] = 50
df

                     사고(건)  사망(명)  부상(명)     A     B
연월
2016년1월              192.0    5.0  387.0   NaN   NaN
2016년2월              174.0    6.0  328.0   NaN   NaN
2016년3월              217.0    7.0  435.0   NaN   NaN
2016년4월              216.0    7.0  419.0   NaN   NaN
2016년5월              239.0   13.0  522.0   NaN   NaN
2016년6월              200.0   12.0  362.0   NaN   NaN
2016년7월              227.0    9.0  460.0   NaN   NaN
2016년8월              230.0    7.0  490.0   NaN   NaN
2016년9월              187.0   13.0  347.0   NaN   NaN
2016년10월             183.0   10.0  367.0   NaN   NaN
2016년11월             200.0    5.0  418.0   NaN   NaN
2016년12월             168.0    4.0  364.0   NaN   NaN
2024-01-02             NaN    NaN    NaN  10.0   NaN
2024-01-03 00:00:00    NaN    NaN    NaN   NaN  50.0

In [236]:
df.at[df.index[-1], df.columns[-1]] = 230
df

                     사고(건)  사망(명)  부상(명)     A      B
연월
2016년1월              192.0    5.0  387.0   NaN    NaN
2016년2월              174.0    6.0  328.0   NaN    NaN
2016년3월              217.0    7.0  435.0   NaN    NaN
2016년4월              216.0    7.0  419.0   NaN    NaN
2016년5월              239.0   13.0  522.0   NaN    NaN
2016년6월              200.0   12.0  362.0   NaN    NaN
2016년7월              227.0    9.0  460.0   NaN    NaN
2016년8월              230.0    7.0  490.0   NaN    NaN
2016년9월              187.0   13.0  347.0   NaN    NaN
2016년10월             183.0   10.0  367.0   NaN    NaN
2016년11월             200.0    5.0  418.0   NaN    NaN
2016년12월             168.0    4.0  364.0   NaN    NaN
2024-01-02             NaN    NaN    NaN  10.0    NaN
2024-01-03 00:00:00    NaN    NaN    NaN   NaN  230.0

In [237]:
df.iloc[1, 2] = 60
df

                     사고(건)  사망(명)  부상(명)     A      B
연월
2016년1월              192.0    5.0  387.0   NaN    NaN
2016년2월              174.0    6.0   60.0   NaN    NaN
2016년3월              217.0    7.0  435.0   NaN    NaN
2016년4월              216.0    7.0  419.0   NaN    NaN
2016년5월              239.0   13.0  522.0   NaN    NaN
2016년6월              200.0   12.0  362.0   NaN    NaN
2016년7월              227.0    9.0  460.0   NaN    NaN
2016년8월              230.0    7.0  490.0   NaN    NaN
2016년9월              187.0   13.0  347.0   NaN    NaN
2016년10월             183.0   10.0  367.0   NaN    NaN
2016년11월             200.0    5.0  418.0   NaN    NaN
2016년12월             168.0    4.0  364.0   NaN    NaN
2024-01-02             NaN    NaN    NaN  10.0    NaN
2024-01-03 00:00:00    NaN    NaN    NaN   NaN  230.0

In [238]:
df.iloc[:, 4] = [500] * len(df)
df

                     사고(건)  사망(명)  부상(명)     A      B
연월
2016년1월              192.0    5.0  387.0   NaN  500.0
2016년2월              174.0    6.0   60.0   NaN  500.0
2016년3월              217.0    7.0  435.0   NaN  500.0
2016년4월              216.0    7.0  419.0   NaN  500.0
2016년5월              239.0   13.0  522.0   NaN  500.0
2016년6월              200.0   12.0  362.0   NaN  500.0
2016년7월              227.0    9.0  460.0   NaN  500.0
2016년8월              230.0    7.0  490.0   NaN  500.0
2016년9월              187.0   13.0  347.0   NaN  500.0
2016년10월             183.0   10.0  367.0   NaN  500.0
2016년11월             200.0    5.0  418.0   NaN  500.0
2016년12월             168.0    4.0  364.0   NaN  500.0
2024-01-02             NaN    NaN    NaN  10.0  500.0
2024-01-03 00:00:00    NaN    NaN    NaN   NaN  500.0

In [239]:
df.iat[3, 3] = 150
df

                     사고(건)  사망(명)  부상(명)      A      B
연월
2016년1월              192.0    5.0  387.0    NaN  500.0
2016년2월              174.0    6.0   60.0    NaN  500.0
2016년3월              217.0    7.0  435.0    NaN  500.0
2016년4월              216.0    7.0  419.0  150.0  500.0
2016년5월              239.0   13.0  522.0    NaN  500.0
2016년6월              200.0   12.0  362.0    NaN  500.0
2016년7월              227.0    9.0  460.0    NaN  500.0
2016년8월              230.0    7.0  490.0    NaN  500.0
2016년9월              187.0   13.0  347.0    NaN  500.0
2016년10월             183.0   10.0  367.0    NaN  500.0
2016년11월             200.0    5.0  418.0    NaN  500.0
2016년12월             168.0    4.0  364.0    NaN  500.0
2024-01-02             NaN    NaN    NaN   10.0  500.0
2024-01-03 00:00:00    NaN    NaN    NaN    NaN  500.0

In [240]:
df.iloc[:, 4] = 600
df

                     사고(건)  사망(명)  부상(명)      A      B
연월
2016년1월              192.0    5.0  387.0    NaN  600.0
2016년2월              174.0    6.0   60.0    NaN  600.0
2016년3월              217.0    7.0  435.0    NaN  600.0
2016년4월              216.0    7.0  419.0  150.0  600.0
2016년5월              239.0   13.0  522.0    NaN  600.0
2016년6월              200.0   12.0  362.0    NaN  600.0
2016년7월              227.0    9.0  460.0    NaN  600.0
2016년8월              230.0    7.0  490.0    NaN  600.0
2016년9월              187.0   13.0  347.0    NaN  600.0
2016년10월             183.0   10.0  367.0    NaN  600.0
2016년11월             200.0    5.0  418.0    NaN  600.0
2016년12월             168.0    4.0  364.0    NaN  600.0
2024-01-02             NaN    NaN    NaN   10.0  600.0
2024-01-03 00:00:00    NaN    NaN    NaN    NaN  600.0

In [241]:
import numpy as np
import pandas as pd

dates = pd.date_range("20250302", periods=7, freq='W-MON')
df = pd.DataFrame(np.arange(35).reshape(7, 5), index=dates, columns=list('ABCDE'))
df

             A   B   C   D   E
2025-03-03   0   1   2   3   4
2025-03-10   5   6   7   8   9
2025-03-17  10  11  12  13  14
2025-03-24  15  16  17  18  19
2025-03-31  20  21  22  23  24
2025-04-07  25  26  27  28  29
2025-04-14  30  31  32  33  34

In [242]:
subdates = pd.date_range("20250307", periods=5, freq='W-MON')
subdates

DatetimeIndex(['2025-03-10', '2025-03-17', '2025-03-24', '2025-03-31',
               '2025-04-07'],
              dtype='datetime64[ns]', freq='W-MON')

In [243]:
s = pd.Series(np.linspace(10, 17, 5), index=subdates)
s

2025-03-10    10.00
2025-03-17    11.75
2025-03-24    13.50
2025-03-31    15.25
2025-04-07    17.00
Freq: W-MON, dtype: float64

In [244]:
df['F'] = s
df

             A   B   C   D   E      F
2025-03-03   0   1   2   3   4    NaN
2025-03-10   5   6   7   8   9  10.00
2025-03-17  10  11  12  13  14  11.75
2025-03-24  15  16  17  18  19  13.50
2025-03-31  20  21  22  23  24  15.25
2025-04-07  25  26  27  28  29  17.00
2025-04-14  30  31  32  33  34    NaN

In [245]:
df2 = df.copy()
df2.iloc[3, 4] = np.nan
df2.iloc[1, :] = np.nan
df2

               A     B     C     D     E      F
2025-03-03   0.0   1.0   2.0   3.0   4.0    NaN
2025-03-10   NaN   NaN   NaN   NaN   NaN    NaN
2025-03-17  10.0  11.0  12.0  13.0  14.0  11.75
2025-03-24  15.0  16.0  17.0  18.0   NaN  13.50
2025-03-31  20.0  21.0  22.0  23.0  24.0  15.25
2025-04-07  25.0  26.0  27.0  28.0  29.0  17.00
2025-04-14  30.0  31.0  32.0  33.0  34.0    NaN

In [246]:
pd.isna(df2)

                A      B      C      D      E      F
2025-03-03  False  False  False  False  False   True
2025-03-10   True   True   True   True   True   True
2025-03-17  False  False  False  False  False  False
2025-03-24  False  False  False  False   True  False
2025-03-31  False  False  False  False  False  False
2025-04-07  False  False  False  False  False  False
2025-04-14  False  False  False  False  False   True

In [247]:
df2.isna()

                A      B      C      D      E      F
2025-03-03  False  False  False  False  False   True
2025-03-10   True   True   True   True   True   True
2025-03-17  False  False  False  False  False  False
2025-03-24  False  False  False  False   True  False
2025-03-31  False  False  False  False  False  False
2025-04-07  False  False  False  False  False  False
2025-04-14  False  False  False  False  False   True

In [248]:
df2.isnull()

                A      B      C      D      E      F
2025-03-03  False  False  False  False  False   True
2025-03-10   True   True   True   True   True   True
2025-03-17  False  False  False  False  False  False
2025-03-24  False  False  False  False   True  False
2025-03-31  False  False  False  False  False  False
2025-04-07  False  False  False  False  False  False
2025-04-14  False  False  False  False  False   True

In [249]:
df2.count()

A    6
B    6
C    6
D    6
E    5
F    4
dtype: int64

In [250]:
df2.count(axis=1)

2025-03-03    5
2025-03-10    0
2025-03-17    6
2025-03-24    5
2025-03-31    6
2025-04-07    6
2025-04-14    5
Freq: W-MON, dtype: int64

In [251]:
s = df2.E.value_counts()
s

E
4.0     1
14.0    1
24.0    1
29.0    1
34.0    1
Name: count, dtype: int64

In [252]:
type(s)
s[4]
s.values
df2['D'].value_counts()
df2['D'].value_counts().to_frame()
df2.E.value_counts(dropna=False)

E
NaN     2
4.0     1
14.0    1
24.0    1
29.0    1
34.0    1
Name: count, dtype: int64

In [253]:
s[4]

np.int64(1)

In [254]:
s.values

array([1, 1, 1, 1, 1])

In [255]:
df2['D'].value_counts()

D
3.0     1
13.0    1
18.0    1
23.0    1
28.0    1
33.0    1
Name: count, dtype: int64

In [256]:
df2['D'].value_counts().to_frame()

      count
D
3.0       1
13.0      1
18.0      1
23.0      1
28.0      1
33.0      1

In [257]:
df2.E.value_counts(dropna=False)

E
NaN     2
4.0     1
14.0    1
24.0    1
29.0    1
34.0    1
Name: count, dtype: int64

In [258]:
s1 = df2.value_counts()

In [259]:
s1

A     B     C     D     E     F
10.0  11.0  12.0  13.0  14.0  11.75    1
20.0  21.0  22.0  23.0  24.0  15.25    1
25.0  26.0  27.0  28.0  29.0  17.00    1
Name: count, dtype: int64

In [260]:
df2.value_counts(dropna=False)

A     B     C     D     E     F
0.0   1.0   2.0   3.0   4.0   NaN      1
10.0  11.0  12.0  13.0  14.0  11.75    1
15.0  16.0  17.0  18.0  NaN   13.50    1
20.0  21.0  22.0  23.0  24.0  15.25    1
25.0  26.0  27.0  28.0  29.0  17.00    1
30.0  31.0  32.0  33.0  34.0  NaN      1
NaN   NaN   NaN   NaN   NaN   NaN      1
Name: count, dtype: int64

In [261]:
s1.index

MultiIndex([(10.0, 11.0, 12.0, 13.0, 14.0, 11.75),
            (20.0, 21.0, 22.0, 23.0, 24.0, 15.25),
            (25.0, 26.0, 27.0, 28.0, 29.0,  17.0)],
           names=['A', 'B', 'C', 'D', 'E', 'F'])

In [262]:
s1.values

array([1, 1, 1])

In [263]:
df2.dropna()

               A     B     C     D     E      F
2025-03-17  10.0  11.0  12.0  13.0  14.0  11.75
2025-03-31  20.0  21.0  22.0  23.0  24.0  15.25
2025-04-07  25.0  26.0  27.0  28.0  29.0  17.00

In [264]:
df2.dropna(axis=0)

               A     B     C     D     E      F
2025-03-17  10.0  11.0  12.0  13.0  14.0  11.75
2025-03-31  20.0  21.0  22.0  23.0  24.0  15.25
2025-04-07  25.0  26.0  27.0  28.0  29.0  17.00

In [265]:
df2.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [2025-03-03 00:00:00, 2025-03-10 00:00:00, 2025-03-17 00:00:00, 2025-03-24 00:00:00, 2025-03-31 00:00:00, 2025-04-07 00:00:00, 2025-04-14 00:00:00]

In [266]:
df2[ df2.isna() ] = 500
df2

                A      B      C      D      E       F
2025-03-03    0.0    1.0    2.0    3.0    4.0  500.00
2025-03-10  500.0  500.0  500.0  500.0  500.0  500.00
2025-03-17   10.0   11.0   12.0   13.0   14.0   11.75
2025-03-24   15.0   16.0   17.0   18.0  500.0   13.50
2025-03-31   20.0   21.0   22.0   23.0   24.0   15.25
2025-04-07   25.0   26.0   27.0   28.0   29.0   17.00
2025-04-14   30.0   31.0   32.0   33.0   34.0  500.00

In [267]:
df = pd.DataFrame([[np.nan, 2, np.nan, 0],
                   [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, np.nan],
                   [np.nan, 3, np.nan, 4]],
                  columns=list("ABCD"))
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [268]:
df.fillna(10)

      A     B     C     D
0  10.0   2.0  10.0   0.0
1   3.0   4.0  10.0   1.0
2  10.0  10.0  10.0  10.0
3  10.0   3.0  10.0   4.0

In [269]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [270]:
df.fillna('missing', axis=0)

         A        B        C        D
0  missing      2.0  missing      0.0
1      3.0      4.0  missing      1.0
2  missing  missing  missing  missing
3  missing      3.0  missing      4.0

In [271]:
df.fillna('missing', limit=1)

         A        B        C        D
0  missing      2.0  missing      0.0
1      3.0      4.0      NaN      1.0
2      NaN  missing      NaN  missing
3      NaN      3.0      NaN      4.0

In [272]:
df.fillna('missing', limit=1, axis=1)

         A    B        C    D
0  missing  2.0      NaN  0.0
1      3.0  4.0  missing  1.0
2  missing  NaN      NaN  NaN
3  missing  3.0      NaN  4.0

In [273]:
df.fillna('value', axis=1)

       A      B      C      D
0  value    2.0  value    0.0
1    3.0    4.0  value    1.0
2  value  value  value  value
3  value    3.0  value    4.0

In [274]:
values = {"A": 100, "B": 200, "C": 300, "D": 400}
df.fillna(value=values)

       A      B      C      D
0  100.0    2.0  300.0    0.0
1    3.0    4.0  300.0    1.0
2  100.0  200.0  300.0  400.0
3  100.0    3.0  300.0    4.0

In [275]:
df.fillna(value=values, limit=2)

       A      B      C      D
0  100.0    2.0  300.0    0.0
1    3.0    4.0  300.0    1.0
2  100.0  200.0    NaN  400.0
3    NaN    3.0    NaN    4.0

In [276]:
s = pd.Series([100, 200, 400], index=list('ACD'))
s

A    100
C    200
D    400
dtype: int64

In [277]:
df.fillna(value=s, limit=1)

       A    B      C      D
0  100.0  2.0  200.0    0.0
1    3.0  4.0    NaN    1.0
2    NaN  NaN    NaN  400.0
3    NaN  3.0    NaN    4.0

In [278]:
df2 = pd.DataFrame(-np.ones((4, 4)), columns=list("ABCE"))
df2

     A    B    C    E
0 -1.0 -1.0 -1.0 -1.0
1 -1.0 -1.0 -1.0 -1.0
2 -1.0 -1.0 -1.0 -1.0
3 -1.0 -1.0 -1.0 -1.0

In [279]:
df.fillna(df2)

     A    B    C    D
0 -1.0  2.0 -1.0  0.0
1  3.0  4.0 -1.0  1.0
2 -1.0 -1.0 -1.0  NaN
3 -1.0  3.0 -1.0  4.0

In [280]:
df.fillna(method='ffill')

/tmp/ipykernel_679/1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  4.0 NaN  1.0
3  3.0  3.0 NaN  4.0

In [281]:
df.fillna(method='ffill', limit=1)

/tmp/ipykernel_679/3640860781.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', limit=1)

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  4.0 NaN  1.0
3  NaN  3.0 NaN  4.0

In [282]:
df.fillna(method='bfill', limit=1)

/tmp/ipykernel_679/3785261496.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill', limit=1)

     A    B   C    D
0  3.0  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  3.0 NaN  4.0
3  NaN  3.0 NaN  4.0

In [283]:
df.mean()

A    3.000000
B    3.000000
C         NaN
D    1.666667
dtype: float64

In [284]:
df.fillna(df.mean())

     A    B   C         D
0  3.0  2.0 NaN  0.000000
1  3.0  4.0 NaN  1.000000
2  3.0  3.0 NaN  1.666667
3  3.0  3.0 NaN  4.000000

In [285]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [286]:
df.fillna(df.mean()['A':'B'])

     A    B   C    D
0  3.0  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  3.0 NaN  NaN
3  3.0  3.0 NaN  4.0

In [287]:
df.fillna(df.mean()['D'])

          A         B         C         D
0  1.666667  2.000000  1.666667  0.000000
1  3.000000  4.000000  1.666667  1.000000
2  1.666667  1.666667  1.666667  1.666667
3  1.666667  3.000000  1.666667  4.000000

In [288]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [289]:
df.fillna(df.mean()['D'], limit=1)

          A         B         C         D
0  1.666667  2.000000  1.666667  0.000000
1  3.000000  4.000000       NaN  1.000000
2       NaN  1.666667       NaN  1.666667
3       NaN  3.000000       NaN  4.000000

In [290]:
df.fillna(df.mean()['D'], limit=1, axis=0)

          A         B         C         D
0  1.666667  2.000000  1.666667  0.000000
1  3.000000  4.000000       NaN  1.000000
2       NaN  1.666667       NaN  1.666667
3       NaN  3.000000       NaN  4.000000

In [291]:
df.fillna(df.mean()['D'], limit=1, axis=1)

          A    B         C    D
0  1.666667  2.0       NaN  0.0
1  3.000000  4.0  1.666667  1.0
2  1.666667  NaN       NaN  NaN
3  1.666667  3.0       NaN  4.0